<a href="https://colab.research.google.com/github/mohanvenkat1/ML_Assignments/blob/main/61Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perform arithmetic operations on NumPy arrays.

In [1]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
add_result = arr1 + arr2
print("Addition:", add_result)
sub_result = arr1 - arr2
print("Subtraction:", sub_result)
mul_result = arr1 * arr2
print("Multiplication:", mul_result)
div_result = arr1 / arr2
print("Division:", div_result)

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]


Write a script to compute the mean and standard deviation of a NumPy array.

In [7]:
a=np.array([1,3,5,7,9])
sum=0
for i in a:
  sum=sum+i;
n=a.size
print("mean=",(sum/n))
print("standard deviation=",np.std(a))

mean= 5.0
standard deviation= 2.8284271247461903


Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [6]:
arr = np.arange(10, 51, 5)
print(arr)


[10 15 20 25 30 35 40 45 50]


Reshape the array into a 2x4 matrix.

In [11]:
arr=np.array([9,8,7,6,5,4,3,2])
print(arr)
print("\nResized to 2x4 matrix\n")
resize=arr.reshape(2,4)
print(resize)

[9 8 7 6 5 4 3 2]

Resized to 2x4 matrix

[[9 8 7 6]
 [5 4 3 2]]


Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("array=\n",arr)
a=arr[1:,1:]
print("sub matrix=\n",a)
arr[arr>4]=0
print("replaced matrix=\n",arr)

array=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
sub matrix=
 [[5 6]
 [8 9]]
replaced matrix=
 [[1 2 3]
 [4 0 0]
 [0 0 0]]


Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division.

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Element-wise Addition:", a+b)
print("Element-wise Multiplication:", a*b)
print("Element-wise Division:", a/b)

Element-wise Addition: [5 7 9]
Element-wise Multiplication: [ 4 10 18]
Element-wise Division: [0.25 0.4  0.5 ]


 Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.

In [18]:
arr = np.random.rand(4, 4)
print("Random array : \n",arr ,"\n\n")
print("Mean of the entire array:", np.mean(arr))
print("Maximum value of the entire array:", np.max(arr))
print("Sum of all elements:", np.sum(arr))


Random array : 
 [[0.91983142 0.52235192 0.44932548 0.23526419]
 [0.91003619 0.38037998 0.98428879 0.71141964]
 [0.20104964 0.05088655 0.03198755 0.90436759]
 [0.75202693 0.37841271 0.70666168 0.30253943]] 


Mean of the entire array: 0.527551855896107
Maximum value of the entire array: 0.9842887850455077
Sum of all elements: 8.440829694337712


 Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [20]:
arr = np.array([1, 2, 3, 4])
print("adding 10 : ",arr+10)
print("multiply by 2 : ",arr*2)
result=2*(arr+10)
print("adding 10 each and multiplying by 2 : ",result)

adding 10 :  [11 12 13 14]
multiply by 2 :  [2 4 6 8]
adding 10 each and multiplying by 2 :  [22 24 26 28]


 Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.


In [23]:
arr = np.random.randint(1, 101, size=(3, 4, 5))
print("Random Array of shape(3,4,5):\n\n", arr)
second_layer = arr[1]
print("\nSecond Layer in the first dimention :\n\n", second_layer)
first_two_rows_last_three_columns = arr[:, :2, -3:]
print("\nFirst Two Rows and Last Three Columns from Each Layer:\n\n", first_two_rows_last_three_columns)
arr[arr % 3 == 0] = -1
print("\nArray After Replacing Elements Divisible by 3 with -1:\n\n", arr)

Random Array of shape(3,4,5):

 [[[36  9 67 85  9]
  [35 57 91 80 10]
  [42 70 96 29 13]
  [60 72 58 23  4]]

 [[68 68 67  2 26]
  [41 88 26 75 30]
  [29 95 45 79 74]
  [62 68 89 99 57]]

 [[94 50 74 37  5]
  [97 61  9 11 20]
  [62 42 68 52 74]
  [49 55 50 74 63]]]

Second Layer in the first dimention :

 [[68 68 67  2 26]
 [41 88 26 75 30]
 [29 95 45 79 74]
 [62 68 89 99 57]]

First Two Rows and Last Three Columns from Each Layer:

 [[[67 85  9]
  [91 80 10]]

 [[67  2 26]
  [26 75 30]]

 [[74 37  5]
  [ 9 11 20]]]

Array After Replacing Elements Divisible by 3 with -1:

 [[[-1 -1 67 85 -1]
  [35 -1 91 80 10]
  [-1 70 -1 29 13]
  [-1 -1 58 23  4]]

 [[68 68 67  2 26]
  [41 88 26 -1 -1]
  [29 95 -1 79 74]
  [62 68 89 -1 -1]]

 [[94 50 74 37  5]
  [97 61 -1 11 20]
  [62 -1 68 52 74]
  [49 55 50 74 -1]]]


 Work with broadcasting and advanced operations in NumPy.
Create a NumPy array arr of shape (3, 3) with random integers between  
1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise
normalization).
• Create a new array by squaring all the elements in arr.
• Find the indices of the top 3 maximum values in the entire array.

In [29]:
arr=np.random.randint(1,20,size=(3,3))
print(arr)
print("after subtracting mean:\n")
row1=arr[0:1]-np.mean(arr[0:1])
row2=arr[1:2]-np.mean(arr[1:2])
row3=arr[2:3]-np.mean(arr[2:3])
print(row1,"\n",row2,"\n",row3)
squared_elements=arr*arr
print("\n\nsquared array:\n\n",squared_elements)
top_indices = np.argsort(arr, axis=None)[-3:]


top_2d_indices = np.unravel_index(top_indices, arr.shape)


print("\nTop 3 indices:\n\n", list(zip(top_2d_indices[0], top_2d_indices[1])))
print("\nTop 3 values:\n\n", arr[top_2d_indices])

[[15  7 12]
 [13  9 19]
 [ 6  9  3]]
after subtracting mean:

[[ 3.66666667 -4.33333333  0.66666667]] 
 [[-0.66666667 -4.66666667  5.33333333]] 
 [[ 0.  3. -3.]]


squared array:

 [[225  49 144]
 [169  81 361]
 [ 36  81   9]]

Top 3 indices:

 [(1, 0), (0, 0), (1, 2)]

Top 3 values:

 [13 15 19]
